### ISSUE TITLE
OTA Bitmapping with JSON array

### ISSUE THREAD

**Issue by dbk1214** [awsdocs/aws-freertos-docs#1]
The bitmap for OTA seems like it is behaving differently for me in that with the documentation it says:

{"b" : binary }

I have to treat my bitmap like a JSON array i.e.

{"b": [255,255,255] } //for 24 blocks for instance 

where the array size is determined by (number of blocks)/8  

so array index 1 has blocks 8-15 for example

is this the way to deal with bitmapping?

**Comment by ericharmeling** [comment]
@dbk1214 

Thank you for opening a doc issue!
Apologies for taking so long to get back to you.

I might need a little more context... Where in the documentation are you reading instructions for OTA bitmapping?

Thanks,
Eric
