### ISSUE TITLE
Wrong chip referred in the ESP32 pages

### ISSUE THREAD

**Issue by gherlein** [awsdocs/aws-freertos-docs#10]
https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_esp32wroom-32se.html

Under "Download and configure FreeRTOS" there is a sectional copy and paste error referring to the ATECC608A part from Microchip.  This page is about the Espressif ESP32.  That section is completely wrong.

**Comment by robhath** [comment]
The ESP32-WROOM-32SE has an integrated ATECC608A chip. Please see https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32se_datasheet_en.pdf
