### ISSUE TITLE
Wrong source file to set up IDE test project for Wi-Fi library

### ISSUE THREAD

**Issue by tu-thai** [awsdocs/aws-freertos-docs#11]
In `afr-porting-wifi.md` (commit 130ad25), to set up the Wi-Fi library in the IDE project, it reads:

> Add the source file `aws_test_wifi.c` to the `aws_tests` IDE project.

But there is no `aws_test_wifi.c` found in the amazon-freertos source version 202012.00.

**Comment by robhath** [comment]
This file has been removed. We do appreciate you pointing out the error and apologize for taking so long to resolve.
