### ISSUE TITLE
Latest OTA create role documentation is missing iam:PassRole

### ISSUE THREAD

**Issue by btashton** [awsdocs/aws-freertos-docs#2]
The commit c031cc00a81d4482bedaa2ab0bc98117cb21b850 update to `aws-freertos-docs/doc_source/create-service-role.md` removed the permissions `PassRole` from the policy document.  It appears that this is still required as without it submitting the OTA job results in this error:
```
        "otaUpdateStatus": "CREATE_FAILED",
        "errorInfo": {
            "code": "AWSIotException",
            "message": "User: arn:aws:sts::<account_id>:assumed-role/iot-ota/#### is not authorized to perform: iam:PassRole on resource: arn:aws:iam::<account_id>:role/iot-ota (Service: AWSIot; Status Code: 403; Error Code: AccessDeniedException; Request ID: <req_id>)"
        }
```

When the role is created according to the previous documentation updates are able to be submitted successfully.

**Comment by ericharmeling** [comment]
@btashton 
Hi Brennan,

Thanks for opening this issue. I've updated the doc to include both of the policy documents that were documented before this update. That update should be published to live docs sometime within the next couple hours.

We really appreciate your feedback! Let me know if you run into any other doc-related issues.

Cheers,
Eric
