### ISSUE TITLE
Acm command does not work with AWS CLI v2

### ISSUE THREAD

**Issue by massi-ang** [awsdocs/aws-freertos-docs#6]
AWS CLI v2 changes the way that b64 encoded files are read (https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam) and that breaks the `acm import-certificate` command syntax used in the examples.

The correct way to import certificates in the v2 CLI is:

`aws acm import-certificate --certificate fileb://... --private-key fileb://... `

This works also in v1.

**Comment by robhath** [comment]
The changes have been incorporated into the documentation.
